from enum import Enum


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    PROCESSING = "PROCESSING"
    OCR_PROCESSING = "OCR_PROCESSING"
    EXTRACTING = "EXTRACTING"
    MATCHING_ANSWERS = "MATCHING_ANSWERS"
    VALIDATING_RESULTS = "VALIDATING_RESULTS"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"


class QuestionStatus(str, Enum):
    EXTRACTED = "EXTRACTED"
    PARTIAL = "PARTIAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    INVALID = "INVALID"


class QuestionType(str, Enum):
    MCQ = "MCQ"
    MULTIPLE_SELECT = "MULTIPLE_SELECT"
    TRUE_FALSE = "TRUE_FALSE"
    FILL_BLANK = "FILL_BLANK"
    DESCRIPTIVE = "DESCRIPTIVE"
    UNKNOWN = "UNKNOWN"


class WarningType(str, Enum):
    OCR_ERROR = "OCR_ERROR"
    MISSING_QUESTION_NUMBER = "MISSING_QUESTION_NUMBER"
    AMBIGUOUS_BOUNDARY = "AMBIGUOUS_BOUNDARY"
    MISSING_OPTION = "MISSING_OPTION"
    MISSING_ANSWER = "MISSING_ANSWER"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    ANSWER_MISMATCH = "ANSWER_MISMATCH"
    CROSS_PAGE_QUESTION = "CROSS_PAGE_QUESTION"
    IMAGE_CONTENT = "IMAGE_CONTENT"
    TABLE_CONTENT = "TABLE_CONTENT"
    POSSIBLE_OCR_ERROR = "POSSIBLE_OCR_ERROR"


class WarningSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class DocumentRelationshipType(str, Enum):
    QUESTION_PAPER = "QUESTION_PAPER"
    ANSWER_KEY = "ANSWER_KEY"
    SUPPLEMENT = "SUPPLEMENT"


class ProcessingStage(str, Enum):
    VALIDATING = "VALIDATING"
    EXTRACTING_PAGES = "EXTRACTING_PAGES"
    PREPROCESSING = "PREPROCESSING"
    OCR = "OCR"
    TEXT_NORMALIZATION = "TEXT_NORMALIZATION"
    QUESTION_SEGMENTATION = "QUESTION_SEGMENTATION"
    QUESTION_EXTRACTION = "QUESTION_EXTRACTION"
    ANSWER_KEY = "ANSWER_KEY"
    MATCHING = "MATCHING"
    VALIDATION = "VALIDATION"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    STARTED = "STARTED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    RETRY = "RETRY"
